In [ ]:
!pip install datasets

In [ ]:
# Import necessary libraries
from datasets import load_dataset
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load the dataset
dataset = load_dataset("cifar10")

In [ ]:
# Import necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
# @title Archive
import numpy as np
batch_images = np.zeros((256, 64, 64, 3))

In [ ]:
# @title Archive
import time
sum = 0

a = time.time()
for i in list(np.arange(1000000)):
  sum = i+sum
b = time.time()
print(b - a)

In [ ]:
from datasets import load_dataset
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np

# Load the CIFAR-10 dataset
dataset = load_dataset("cifar10")

# Preprocess the dataset: Convert images to NumPy arrays and flatten
def preprocess_images(images):
    # Convert each image to a NumPy array and flatten it
    return np.array([np.array(image).flatten() for image in images])

def preprocess_labels(labels):
    return np.array(labels)

# Correctly accessing the 'img' and 'label' keys
X_train = preprocess_images(dataset['train']['img'])
y_train = preprocess_labels(dataset['train']['label'])
X_test = preprocess_images(dataset['test']['img'])
y_test = preprocess_labels(dataset['test']['label'])

# RandomForestClassifier
random_forest_model = RandomForestClassifier(n_estimators=100, random_state=42)
random_forest_model.fit(X_train, y_train)
y_pred_rf = random_forest_model.predict(X_test)
print("Random Forest Classifier")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))

# LogisticRegression
logistic_regression_model = LogisticRegression(max_iter=200, multi_class='multinomial', solver='lbfgs', random_state=42, n_jobs=-1)
logistic_regression_model.fit(X_train, y_train)
y_pred_lr = logistic_regression_model.predict(X_test)
print("Logistic Regression")
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))
print("Classification Report:\n", classification_report(y_test, y_pred_lr))




Random Forest Classifier
Accuracy: 0.471
Confusion Matrix:
 [[578  38  49  11  28  25  25  30 150  66]
 [ 31 552  21  28  19  32  42  28  55 192]
 [104  42 348  79 137  55 124  57  26  28]
 [ 53  41  80 269  76 203 129  61  17  71]
 [ 52  22 124  61 408  46 156  86  20  25]
 [ 36  32  90 172  64 384  87  86  28  21]
 [ 12  35  77  79 110  51 555  31  14  36]
 [ 53  42  45  65 109  74  45 455  23  89]
 [ 88  85  17  26  19  38  12  22 617  76]
 [ 50 178  14  29  20  21  25  39  80 544]]
Classification Report:
               precision    recall  f1-score   support

           0       0.55      0.58      0.56      1000
           1       0.52      0.55      0.53      1000
           2       0.40      0.35      0.37      1000
           3       0.33      0.27      0.30      1000
           4       0.41      0.41      0.41      1000
           5       0.41      0.38      0.40      1000
           6       0.46      0.56      0.50      1000
           7       0.51      0.46      0.48      100

In [ ]:
# @title Archive
import numpy as np
dataset = load_dataset("cifar10")
X_train0 = dataset['train']['img']
X_train = [np.array(x).flatten() for x in X_train0]

X_test0 = dataset['test']['img']
X_test = [np.array(x).flatten() for x in X_test0]

In [ ]:
# @title Archive
import tensorflow as tf
y_train = np.array(dataset['train']['label'])
y_test = np.array(dataset['test']['label'])

model = tf.keras.applications.resnet50.ResNet50(
  include_top=False, # take any input shape, not just 224x224
  weights='imagenet', # use the imagenet pretrained model
  pooling='avg' # use global average pooling to get a 2048 vector from our image
)

X_test_stack = tf.stack(X_test0)
embedding_test = model.predict(X_test_stack)
X_train_stack = tf.stack(X_train0)
embedding_train = model.predict(X_train_stack)

In [ ]:
# @title Archive
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np
random_forest_model = RandomForestClassifier(n_estimators=100, random_state=42)
random_forest_model.fit(embedding_train, y_train)
y_pred = random_forest_model.predict(embedding_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n",classification_report(y_test, y_pred))

In [ ]:
# @title Archive
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
logistic_regression_model = LogisticRegression(max_iter = 1000, multi_class='multinomial', solver='lbfgs', random_state=42)
logistic_regression_model.fit(embedding_train, y_train)
y_pred = logistic_regression_model.predict(embedding_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))